name: publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest, windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: List directory contents
        run: ls -la
      - name: Navigate to plugin directory
        run: cd Plugin
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies and run commands
        working-directory: ./plugin  # Set working directory to 'plugin'
        run: |
          npm ci
          npm run build --if-present
          npm test
